# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java



resources:         
  repositories:
  - repository: pipelinesJavaIdentifier  
    type: GitHub
    connection: GHC
    source: jainamanjain/pipelines-java

jobs:
- job: BuildRepo
  displayName: Build the project
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: false
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: Readme.md'
    inputs:
      ArtifactName: Readme.md
- job: download_specific_artifact1
  displayName: download specific artifact1
  dependsOn: BuildRepo
  pool:
    name: Default
  steps:
    - download: MyPipeline1
      artifact: Readme.md



